# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Cache to speed up the build
cache: pip

python:
  - "3.8"
before_install:
  - python -m pip install --upgrade pip
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest src/
# travis CI straight to heroku deployment CD
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: $HEROKU_APP_NAME
  run: python src/manage.py migrate
  on:
    repo: ryuzvki221/ProxiDoc
    branch: master
