language: python
cache: pip
python:
  - '3.8'
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt
script:
  - pytest src/
deploy:
  provider: heroku
  api_key:
    secure: Yd1gqHSo5gDI42f40J7HPuovQd2XcXaUu9b/zupVGcdryLX01Rcb+zih5MN+0MCPhHNkqLwoOWc4STWzqcdu9P4X96H9XqqO4ZqQuuw+i/5DJeRBSpe4xanSD9mKktiwOB30SJggiaGmoDFBaiIbCzCtZfxPTFRP8//AfgM60gCSmDHAKC5ZMLlWfpkLVgAwtFNcVOZvUfbHrUQ+W0yJirj11ehsTCCHn9EtGrKrU9b6flvxfORvYvQAh3LLGyvoWhbjQIp2T2iZ74W+bf8GFEm5RN4Q+eTLMFv3M9yn7ADOFPTPT+ulFyY/HoYmvY+dzTcYGkmHvLvnBciXktqqsdSYjX2xDoIhmC1pUp8dOVl+VrxAFxtSj8Jubn6YY32ZU+7EojEPb1NT8GxNVKv/B9xQlgGdEi16AJBlf/0r+Q2l2P6DAebCTg7bfyxcwFN1N7mWSmjMNHvzfKOCJ50uaMLBCjplwbIkAn08n9q/kPKx6cLdrevYhSBjFX7qkg1QrFIhVRCfJ8hKIQjnKqowlAzHByOeLX1gQCBTQZFKXqO5lLauR4d8fMStsnyaAuu2UdQ9LLgKsgo58fVrpzaMyuvEyUXmYogoGZn8/aPE7FnJ2z2WXPZooxASADHcZsIFQTSIKpJXfrxllav3vhG/BwboQPcjRRuRrtGlBsYU6IM=
  strategy: api
  app: proxidoc
  run: python src/manage.py migrate
  on:
    repo: ryuzvki221/ProxiDoc
    branch: master